package commoncrawl

import mock "github.com/stretchr/testify/mock"

// MockOutputFileWriter is an autogenerated mock type for the OutputFileWriter type
type MockOutputFileWriter struct {
	mock.Mock
}

// WriteOutputFile provides a mock function with given fields: filepath, data
func (_m *MockOutputFileWriter) WriteOutputFile(filepath string, data []byte) error {
	ret := _m.Called(filepath, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(filepath, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
